### PR TITLE
Fix/48 remove globalenv

### LINKED ISSUE #48: `get_abcd_raw` and `merge_in_geography` reference `.GlobalEnv`
The functions related to preparing map data still read out-of-scope `.GlobalEnv` variables.

https://github.com/RMI-PACTA/pacta.portfolio.allocate/blob/384e220cb15aee5e9d4e66dfe74b3da3046ead8b/R/get_abcd_raw.R#L15-L21

https://github.com/RMI-PACTA/pacta.portfolio.allocate/blob/384e220cb15aee5e9d4e66dfe74b3da3046ead8b/R/merge_in_geography.R#L22-L23

https://github.com/search?q=repo%3ARMI-PACTA%2Fpacta.portfolio.allocate%20.GlobalEnv&type=code

Discovered in https://github.com/RMI-PACTA/workflow.pacta/pull/64

### PR DESCRIPTION
**Pull request by AlexAxthelm**
Closes #48

### CODE REVIEW

**Comment by AlexAxthelm** [comment]
Runs cleanly in `workflow.pacta`, after some code changes. https://github.com/RMI-PACTA/workflow.pacta/actions/runs/9257776713/job/25466670195?pr=64

**Comment by AlexAxthelm** [comment]
Changes in `workflow.transition.monitor` also run cleanly https://github.com/RMI-PACTA/workflow.transition.monitor/actions/runs/9258060506

https://github.com/RMI-PACTA/workflow.transition.monitor/pull/316

File: DESCRIPTION [hunk 1]
```diff
@@ -1,6 +1,6 @@
 Package: pacta.portfolio.allocate
 Title: pacta.portfolio.allocate
-Version: 0.0.2.9000
+Version: 0.0.2.9001
```
Comment (cjyetman) [inline DESCRIPTION]:
```suggestion
Version: 0.0.2.9000
```

File: R/get_abcd_raw.R [hunk 2]
```diff
@@ -3,26 +3,38 @@
 #' A longer description of the function
 #'
 #' @param portfolio_type A description of the argument
+#' @param data_path Path to directory containing ABCD Data files
```
Comment (cjyetman) [inline R/get_abcd_raw.R]:
```suggestion
#' @param analysis_inputs_path Path to directory containing ABCD Data files
```

File: R/get_abcd_raw.R [hunk 3]
```diff
@@ -3,26 +3,38 @@
...
+#' analysis.
 #'
 #' @return A description of the return value
 #'
 #' @export
 
-get_abcd_raw <- function(portfolio_type) {
+get_abcd_raw <- function(
+  portfolio_type,
+  data_path,
```
Comment (cjyetman) [inline R/get_abcd_raw.R]:
```suggestion
  analysis_inputs_path,
```

File: R/get_abcd_raw.R [hunk 4]
```diff
@@ -3,26 +3,38 @@
...
+  start_year,
+  time_horizon,
+  sector_list
+) {
   filename_eq_raw <- "masterdata_ownership_datastore.rds"
   filename_cb_raw <- "masterdata_debt_datastore.rds"
 
   if (portfolio_type == "Equity") {
-    abcd_raw <- readr::read_rds(file.path(.GlobalEnv$analysis_inputs_path, filename_eq_raw))
+    abcd_raw <- readr::read_rds(file.path(data_path, filename_eq_raw))
```
Comment (cjyetman) [inline R/get_abcd_raw.R]:
```suggestion
    abcd_raw <- readr::read_rds(file.path(analysis_inputs_path, filename_eq_raw))
```

File: R/get_abcd_raw.R [hunk 5]
```diff
@@ -3,26 +3,38 @@
...
   }
 
   if (portfolio_type == "Bonds") {
-    abcd_raw <- readr::read_rds(file.path(.GlobalEnv$analysis_inputs_path, filename_cb_raw))
+    abcd_raw <- readr::read_rds(file.path(data_path, filename_cb_raw))
```
Comment (cjyetman) [inline R/get_abcd_raw.R]:
```suggestion
    abcd_raw <- readr::read_rds(file.path(analysis_inputs_path, filename_cb_raw))
```

File: R/get_abcd_raw.R (hunk 3 above)
Comment (cjyetman) [reply R/get_abcd_raw.R]: `analysis_inputs_path` is used all over the place across multiple repos... I don't want to introduce an additional name for it, bound to cause confusion

**Review by cjyetman — CHANGES_REQUESTED** [review]
see comments

File: DESCRIPTION (hunk 1 above)
Comment (AlexAxthelm) [reply DESCRIPTION]: Doesn't bumping version make sense, given that there's an incompatible signature change on the functions?

Comment (cjyetman) [reply DESCRIPTION]: It's never been done before and I don't intend to do it in the future

Comment (jdhoffa) [reply DESCRIPTION]: My two cents is that this is NIT either way. 

To me, the version `X.Y.Z.9000` indicates that this is a dev version, and may not be compatible with other  `X.Y.Z.9000` versions. 

but ever since https://github.com/RMI-PACTA/actions/blob/main/.github/workflows/R-semver-check.yml , I have personally started bumping the `9000` version on every commit, mainly to satisfy the check. 

So I would suggest just leaving this to @cjyetman's discretion here (as the maintainer).

Comment (AlexAxthelm) [reply DESCRIPTION]: I'm fine with not bumping version here.

The reason I wrote the semver check and like using it is that it is a very clear way to identify not just that something is a dev version, but to specify which dev version is required. 

It's really nice to have something like this:

```
Imports:
  pacta.portfolio.allocate (>= 0.0.2.9001),
```
https://github.com/RMI-PACTA/workflow.pacta/blob/d4edcbba0291bbf56550952796de14fb88f497c4/DESCRIPTION#L32

to flag that there's inconsistencies (and probably errors) if we try to use the older (`.9000`) version.

**Review by cjyetman — APPROVED** [review]

**Review by jdhoffa — APPROVED** [review]
